### ISSUE TITLE
Actividad 7 proposiciones lógicas JUAN PABLO CÉSAR HERNÁNDEZ SANTIAGO 1AS 

### ISSUE THREAD

**Issue by Juan27231** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Juan27231#1]
[ejercicios logica proposicional JUAN PABLO CÉSAR HERNÁNDEZ SANTIAGO.pdf](https://github.com/user-attachments/files/17388339/ejercicios.logica.proposicional.JUAN.PABLO.CESAR.HERNANDEZ.SANTIAGO.pdf)

**Comment by Proyect-A16** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:20/25
Total:95/100

**Comment by josealfredo79** [comment]
bien hecho y revisado..
